version: '3'
services:
  frontend:
    container_name: frontend-frontend-1
    image: shaileshhd/frontend:latest
    build:
      context: ./
      dockerfile: Dockerfile.dev
    ports:
      - 3000:3000
    volumes:
      - /app/node_modules
      - ./:/app
  tests:
    container_name: frontend-test-1
    image: shaileshhd/frontend:latest
    build:
      context: ./
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./:/app
    command: ["npm", "run", "test"]
    